# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER2XML', '0002_auto_20170316_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'documents/')),
            ],
        ),
    ]
